# Configuration file for the Sphinx documentation builder.
# For the full list of built-in configuration values, see:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import os
import sys
sys.path.insert(0, os.path.abspath('../..'))

# -- Project information -----------------------------------------------------
project = 'forex_data'
copyright = '2024, Nicola Fiorato'
author = 'Nicola Fiorato'

version = '0.1'
release = '0.1.1'

# -- General configuration ---------------------------------------------------
extensions = [
    'sphinx.ext.autodoc',           # Auto-generate docs from docstrings
    'sphinx.ext.napoleon',          # Support for Google/NumPy docstrings
    'sphinx.ext.viewcode',          # Add links to source code
    'sphinx.ext.intersphinx',       # Link to other projects' documentation
    'sphinx.ext.todo',              # Support for TODO items
    'sphinx.ext.coverage',          # Check documentation coverage
    'sphinx.ext.githubpages',       # Create .nojekyll for GitHub Pages
    'sphinx_autodoc_typehints',     # Better type hint rendering
    'sphinx_rtd_theme',             # Read the Docs theme
]

templates_path = ['_templates']
exclude_patterns = []

# The suffix(es) of source filenames
source_suffix = '.rst'

# The master toctree document
master_doc = 'index'

# The language for content autogenerated by Sphinx
language = 'en'

# -- Options for HTML output -------------------------------------------------
html_theme = 'sphinx_rtd_theme'
html_static_path = ['_static']

html_theme_options = {
    'navigation_depth': 4,
    'collapse_navigation': False,
    'sticky_navigation': True,
    'includehidden': True,
    'titles_only': False,
    'style_external_links': True,
    'prev_next_buttons_location': 'both',
    'style_nav_header_background': 'linear-gradient(135deg, #2c5aa0 0%, #1a8cff 100%)',
    'logo_only': False,
}

# Add any paths that contain custom static files (such as style sheets)
html_logo = '_static/logo.png'
html_favicon = '_static/favicon.png'

# Custom CSS files
html_css_files = [
    'custom.css',
]

# Additional HTML context
html_context = {
    'display_github': True,
    'github_user': 'nikfio',
    'github_repo': 'forex_data',
    'github_version': 'master',
    'conf_py_path': '/docs/source/',
}

# If true, the reST sources are included in the HTML build as _sources
html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer
html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer
html_show_copyright = True

# -- Options for autodoc -----------------------------------------------------
autodoc_default_options = {
    'members': True,
    'member-order': 'bysource',
    'special-members': '__init__',
    'undoc-members': True,
    'exclude-members': '__weakref__',
    'show-inheritance': True,
}

# Automatically extract typehints when specified
autodoc_typehints = 'description'
autodoc_typehints_description_target = 'documented'

# -- Options for napoleon ----------------------------------------------------
napoleon_google_docstring = True
napoleon_numpy_docstring = False
napoleon_include_init_with_doc = True
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = True
napoleon_use_admonition_for_notes = True
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True
napoleon_preprocess_types = True
napoleon_type_aliases = None
napoleon_attr_annotations = True

# -- Options for intersphinx -------------------------------------------------
intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
    'polars': ('https://pola-rs.github.io/polars/py-polars/html/', None),
    'pandas': ('https://pandas.pydata.org/docs/', None),
    'pyarrow': ('https://arrow.apache.org/docs/', None),
}

# -- Options for todo extension ----------------------------------------------
todo_include_todos = True

# -- Suppress warnings ---------------------------------------------
# Suppress warnings for optional dependencies and type hints
suppress_warnings = [
    'ref.python',  # Duplicate exceptions
    'sphinx_autodoc_typehints.guarded_import',  # Optional deps
    'sphinx_autodoc_typehints.forward_reference',  # Forward refs
]

# Autodoc configuration for handling inherited docstrings
autodoc_inherit_docstrings = True

# -- SEO and Meta information ------------------------------------------------
html_title = 'forex_data - Forex Data Aggregation Library'
html_short_title = 'forex_data'

# Meta tags for SEO
html_meta = {
    'description': (
        'Professional Forex data aggregation library supporting '
        'historical and real-time data with Polars, Pandas, and PyArrow.'
    ),
    'keywords': (
        'forex, data, OHLC, trading, polars, pandas, pyarrow, '
        'historical data, real-time data'
    ),
    'author': 'Nicola Fiorato',
    'og:title': 'forex_data Documentation',
    'og:description': 'Comprehensive Forex data aggregation library for Python',
    'og:type': 'website',
    'twitter:card': 'summary',
}
