---
# yaml document template for data management configuration

TICKER: 'EURUSD'

DATA_FILETYPE: 'parquet'

ENGINE: 'pandas'

PROVIDERS_KEY: 
    ALPHA_VANTAGE_KEY : <ALPHA-VANTAGE-API-KEY>, 
    POLYGON_IO_KEY    : <POLYGON-IO-API-KEY>
    
    
